CREATE TABLE person (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  gender VARCHAR(7) NOT NULL,
  date_of_birth DATE NOT NULL,
  email VARCHAR(150),
  country_of_birth VARCHAR(50)
);

insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Eadmund', 'Dorsey', null, 'MALE', '2022/12/12', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Benjamen', 'Garnson', 'bgarnson1@deviantart.com', 'MALE', '2023/03/18', 'Slovenia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sven', 'Philipsen', 'sphilipsen2@jiathis.com', 'MALE', '2023/11/18', 'Norway');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Mordy', 'Albasini', 'malbasini3@bbc.co.uk', 'MALE', '2023/09/25', 'Belarus');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Arley', 'Naish', 'anaish4@redcross.org', 'MALE', '2023/10/13', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Kim', 'Enriques', 'kenriques5@tmall.com', 'FEMALE', '2023/06/17', 'Australia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Amaleta', 'Jamot', 'ajamot6@hugedomains.com', 'FEMALE', '2023/09/02', 'Jamaica');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Geoffrey', 'Heasly', 'gheasly7@pinterest.com', 'MALE', '2023/11/14', 'Guatemala');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Stavros', 'Mapston', 'smapston8@state.tx.us', 'MALE', '2023/03/10', 'Egypt');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Hebert', 'Duckwith', 'hduckwith9@plala.or.jp', 'MALE', '2023/02/27', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Donny', 'Schoffler', 'dschofflera@sohu.com', 'MALE', '2023/08/02', 'Botswana');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Eolanda', 'Kassman', 'ekassmanb@furl.net', 'FEMALE', '2023/09/21', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marina', 'Crampton', 'mcramptonc@bizjournals.com', 'FEMALE', '2023/01/25', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Domenico', 'Kemston', 'dkemstond@reference.com', 'MALE', '2023/01/09', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Putnam', 'Pirot', 'ppirote@goo.gl', 'MALE', '2023/06/04', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Stern', 'Oldacres', null, 'MALE', '2023/09/22', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Iolanthe', 'Avramovsky', null, 'FEMALE', '2023/09/26', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Siana', 'Woods', null, 'FEMALE', '2023/11/14', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jessie', 'Sleney', 'jsleneyi@moonfruit.com', 'MALE', '2023/08/14', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Aryn', 'Lambourne', 'alambournej@qq.com', 'FEMALE', '2023/06/27', 'Colombia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Daron', 'Woodes', 'dwoodesk@gizmodo.com', 'FEMALE', '2023/09/05', 'Tajikistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Elsa', 'Harrowell', null, 'FEMALE', '2023/03/25', 'Venezuela');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Chiarra', 'Etter', 'cetterm@salon.com', 'FEMALE', '2023/10/20', 'Argentina');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Giusto', 'Elnaugh', 'gelnaughn@webeden.co.uk', 'MALE', '2023/09/02', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Crista', 'Cramond', null, 'FEMALE', '2023/04/14', 'Thailand');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jasmina', 'Mattei', 'jmatteip@intel.com', 'FEMALE', '2023/04/10', 'Samoa');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Fiann', 'Pesik', 'fpesikq@senate.gov', 'FEMALE', '2023/03/07', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Austina', 'Rackam', 'arackamr@irs.gov', 'FEMALE', '2023/01/06', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dannye', 'Gwin', null, 'FEMALE', '2023/11/10', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dilly', 'Ludmann', null, 'MALE', '2023/09/26', 'Mali');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marietta', 'Nadin', 'mnadinu@psu.edu', 'MALE', '2023/05/23', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Josy', 'Walling', 'jwallingv@intel.com', 'FEMALE', '2023/03/10', 'Argentina');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jacquie', 'Musto', 'jmustow@yale.edu', 'FEMALE', '2023/05/21', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Giovanna', 'Lark', 'glarkx@reference.com', 'FEMALE', '2023/09/23', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Gregoire', 'Donke', 'gdonkey@list-manage.com', 'MALE', '2023/10/18', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Padriac', 'Cordery', 'pcorderyz@ibm.com', 'MALE', '2023/08/19', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Thelma', 'Hansley', 'thansley10@forbes.com', 'FEMALE', '2023/08/22', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Kimbell', 'Traut', 'ktraut11@cdbaby.com', 'MALE', '2023/08/05', 'East Timor');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tremain', 'Trapp', 'ttrapp12@mediafire.com', 'MALE', '2023/05/04', 'Thailand');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Avram', 'Giacaponi', 'agiacaponi13@blogspot.com', 'MALE', '2023/07/19', 'Sweden');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Chaunce', 'Dziwisz', null, 'MALE', '2023/11/05', 'Finland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Chad', 'Earney', 'cearney15@princeton.edu', 'MALE', '2023/04/28', 'Iraq');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dyan', 'Heynen', null, 'FEMALE', '2023/07/23', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Brooke', 'Oen', 'boen17@imdb.com', 'MALE', '2023/07/11', 'Afghanistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Mureil', 'Gerrett', null, 'FEMALE', '2023/07/26', 'Serbia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Isaac', 'Broomfield', 'ibroomfield19@goo.gl', 'MALE', '2023/05/12', 'Sweden');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jandy', 'Egle of Germany', null, 'FEMALE', '2023/08/16', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Merrill', 'Fidele', 'mfidele1b@xinhuanet.com', 'FEMALE', '2022/11/24', 'Palestinian Territory');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Alessandro', 'Rodolphe', 'arodolphe1c@slate.com', 'MALE', '2023/08/02', 'Paraguay');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dana', 'Eldin', 'deldin1d@japanpost.jp', 'MALE', '2023/05/19', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Mikkel', 'Nordass', 'mnordass1e@ca.gov', 'MALE', '2023/04/10', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Patrica', 'MacBean', 'pmacbean1f@engadget.com', 'FEMALE', '2023/02/07', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Edythe', 'Besque', null, 'FEMALE', '2023/01/28', 'Croatia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Padgett', 'Treeby', 'ptreeby1h@stumbleupon.com', 'MALE', '2023/02/19', 'Croatia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Martguerita', 'Edelheid', 'medelheid1i@sina.com.cn', 'FEMALE', '2023/11/14', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Gaultiero', 'January', 'gjanuary1j@omniture.com', 'MALE', '2023/10/31', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dayna', 'Bradnock', null, 'FEMALE', '2023/09/03', 'Laos');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ade', 'Worsnap', 'aworsnap1l@woothemes.com', 'MALE', '2023/02/07', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Rafaela', 'Hechlin', 'rhechlin1m@about.me', 'FEMALE', '2023/03/31', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Yalonda', 'Mayou', null, 'FEMALE', '2023/03/29', 'Egypt');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marybeth', 'Pandey', 'mpandey1o@odnoklassniki.ru', 'FEMALE', '2023/08/30', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Shoshana', 'Stoeck', 'sstoeck1p@amazon.co.uk', 'FEMALE', '2023/04/09', 'Panama');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Evania', 'Trundler', 'etrundler1q@homestead.com', 'FEMALE', '2023/07/12', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nichole', 'Banasik', 'nbanasik1r@columbia.edu', 'FEMALE', '2023/11/15', 'Morocco');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Forrester', 'Camoys', 'fcamoys1s@blog.com', 'MALE', '2022/12/14', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Fabio', 'Tremblet', 'ftremblet1t@zdnet.com', 'MALE', '2023/05/09', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Reina', 'Fellow', 'rfellow1u@fastcompany.com', 'FEMALE', '2023/06/06', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Kain', 'Buttrick', null, 'MALE', '2023/04/26', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Allissa', 'Bruck', 'abruck1w@feedburner.com', 'FEMALE', '2022/12/09', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Malinde', 'Klimpt', null, 'FEMALE', '2023/04/16', 'United States');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Rozina', 'Klee', null, 'FEMALE', '2023/09/18', 'Puerto Rico');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tybie', 'Riddoch', null, 'FEMALE', '2022/11/26', 'Ukraine');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Joshua', 'Ricards', 'jricards20@unc.edu', 'MALE', '2023/01/11', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lennard', 'Peele', null, 'MALE', '2023/09/22', 'El Salvador');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Langston', 'Stonehouse', 'lstonehouse22@jimdo.com', 'MALE', '2023/01/26', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ruddy', 'Cleiment', 'rcleiment23@hostgator.com', 'MALE', '2023/06/25', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dion', 'Faint', 'dfaint24@homestead.com', 'MALE', '2022/12/07', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tobe', 'Vahey', null, 'FEMALE', '2023/11/01', 'Greenland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Abigael', 'Blakesley', 'ablakesley26@npr.org', 'FEMALE', '2023/04/17', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Farrel', 'McKag', 'fmckag27@woothemes.com', 'MALE', '2023/02/26', 'Liberia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Carry', 'Mowatt', 'cmowatt28@photobucket.com', 'FEMALE', '2023/08/29', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Milty', 'Souza', null, 'MALE', '2022/12/19', 'Macedonia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ernst', 'Silverthorne', 'esilverthorne2a@state.tx.us', 'MALE', '2023/09/28', 'Costa Rica');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ortensia', 'Antrag', null, 'FEMALE', '2022/11/24', 'Malta');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Minny', 'McGillicuddy', 'mmcgillicuddy2c@elegantthemes.com', 'FEMALE', '2023/10/27', 'Slovenia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marvin', 'Niece', 'mniece2d@usnews.com', 'MALE', '2022/12/20', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Gun', 'Watkiss', 'gwatkiss2e@walmart.com', 'MALE', '2023/03/12', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Benedicto', 'Askin', 'baskin2f@chronoengine.com', 'MALE', '2023/05/18', 'Mexico');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Elie', 'Blakeley', 'eblakeley2g@pagesperso-orange.fr', 'FEMALE', '2023/09/15', 'Germany');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Drusi', 'De Morena', 'ddemorena2h@mashable.com', 'FEMALE', '2023/05/03', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Demott', 'Chess', null, 'MALE', '2023/04/19', 'Malta');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marwin', 'MacGilmartin', 'mmacgilmartin2j@aboutads.info', 'MALE', '2023/10/24', 'Guatemala');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Banky', 'Mountcastle', 'bmountcastle2k@weebly.com', 'MALE', '2023/03/03', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marve', 'West', 'mwest2l@studiopress.com', 'MALE', '2023/03/01', 'Peru');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sibyl', 'Gowthorpe', 'sgowthorpe2m@instagram.com', 'FEMALE', '2023/01/26', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jude', 'Dongall', 'jdongall2n@hao123.com', 'MALE', '2023/10/06', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Wit', 'Esgate', 'wesgate2o@over-blog.com', 'MALE', '2023/07/02', 'South Africa');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Brock', 'Axby', 'baxby2p@archive.org', 'MALE', '2022/11/25', 'Republic of the Congo');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cynthy', 'Kruger', 'ckruger2q@google.com.au', 'FEMALE', '2022/12/27', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dunc', 'Secombe', null, 'MALE', '2023/04/05', 'Israel');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Alric', 'Mungham', null, 'MALE', '2023/02/04', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Betsey', 'Hordle', null, 'FEMALE', '2023/04/17', 'Iran');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dalton', 'Kubicka', 'dkubicka2@dropbox.com', 'MALE', '2023/07/19', 'Morocco');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Shelia', 'Travers', null, 'FEMALE', '2023/11/19', 'Croatia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Myrle', 'Blondelle', 'mblondelle4@sun.com', 'FEMALE', '2023/03/18', 'Uzbekistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Emlen', 'Wheldon', 'ewheldon5@woothemes.com', 'MALE', '2023/03/13', 'Vietnam');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Karlyn', 'Harler', 'kharler6@eepurl.com', 'FEMALE', '2023/09/18', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cathrine', 'Gettone', null, 'FEMALE', '2023/07/09', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Riccardo', 'Rosingdall', 'rrosingdall8@typepad.com', 'MALE', '2023/02/25', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Alfonse', 'Clementi', null, 'MALE', '2023/02/25', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Daveta', 'Bachelar', 'dbachelara@pbs.org', 'FEMALE', '2023/07/17', 'Albania');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Janeta', 'Whiterod', 'jwhiterodb@reference.com', 'FEMALE', '2023/04/10', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Michaeline', 'Lode', 'mlodec@mapquest.com', 'FEMALE', '2023/02/11', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Brigg', 'Seabridge', 'bseabridged@hp.com', 'MALE', '2023/07/19', 'Peru');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jerry', 'Brewins', 'jbrewinse@chron.com', 'MALE', '2023/01/09', 'Tanzania');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Timothy', 'Hof', 'thoff@t-online.de', 'MALE', '2023/07/13', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Bjorn', 'Potell', 'bpotellg@noaa.gov', 'MALE', '2023/10/20', 'Luxembourg');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Pat', 'Docket', 'pdocketh@ox.ac.uk', 'MALE', '2023/09/11', 'Bulgaria');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Hurleigh', 'Deble', 'hdeblei@geocities.com', 'MALE', '2023/08/28', 'Malawi');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Malinde', 'Stacey', 'mstaceyj@npr.org', 'FEMALE', '2023/02/17', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Noak', 'Pietruszka', null, 'MALE', '2022/12/06', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Laney', 'Yerrington', null, 'MALE', '2023/06/25', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lynn', 'Brolechan', 'lbrolechanm@simplemachines.org', 'FEMALE', '2023/08/29', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Anastasie', 'Sommer', null, 'FEMALE', '2023/06/19', 'Ukraine');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sayre', 'Riep', 'sriepo@engadget.com', 'MALE', '2022/12/01', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Kanya', 'Tompsett', 'ktompsettp@ucoz.ru', 'FEMALE', '2023/09/29', 'Thailand');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lewie', 'Winterburn', 'lwinterburnq@usa.gov', 'MALE', '2023/10/25', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Arie', 'Thelwll', 'athelwllr@cbslocal.com', 'MALE', '2023/01/19', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Erin', 'Melia', 'emelias@discuz.net', 'MALE', '2023/09/24', 'Tajikistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Eduino', 'Aven', 'eavent@wix.com', 'MALE', '2023/01/20', 'Colombia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dulcea', 'Minihane', 'dminihaneu@nationalgeographic.com', 'Agender', '2023/06/02', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lavinie', 'Rickardsson', null, 'FEMALE', '2023/05/01', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Krispin', 'Risbridge', 'krisbridgew@microsoft.com', 'FEMALE', '2023/10/25', 'Palestinian Territory');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Merv', 'Dumigan', null, 'MALE', '2023/09/27', 'Libya');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Clarissa', 'Granleese', 'cgranleesey@aboutads.info', 'FEMALE', '2023/01/21', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Meghann', 'Attrey', null, 'MALE', '2023/02/13', 'Afghanistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tobit', 'Povele', 'tpovele10@wsj.com', 'MALE', '2023/05/13', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lindsay', 'Borland', 'lborland11@cargocollective.com', 'FEMALE', '2023/06/19', 'United States');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Greg', 'McSperrin', null, 'MALE', '2023/06/25', 'South Korea');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Regen', 'Vasyunin', 'rvasyunin13@behance.net', 'FEMALE', '2023/06/10', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Corby', 'Burbudge', 'cburbudge14@tuttocitta.it', 'MALE', '2023/02/21', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Thane', 'Elcox', 'telcox15@phoca.cz', 'MALE', '2023/07/24', 'Comoros');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Boyd', 'Margach', 'bmargach16@nature.com', 'MALE', '2023/02/06', 'Armenia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Leigh', 'Kehoe', 'lkehoe17@usatoday.com', 'FEMALE', '2022/12/09', 'Uzbekistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Twyla', 'Menichino', null, 'FEMALE', '2023/08/20', 'Canada');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Valentia', 'Northley', 'vnorthley19@xrea.com', 'FEMALE', '2023/06/22', 'Bolivia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Audrye', 'Macenzy', 'amacenzy1a@virginia.edu', 'FEMALE', '2023/11/21', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ogdan', 'Camidge', null, 'MALE', '2023/10/23', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Isabel', 'McKennan', 'imckennan1c@weebly.com', 'FEMALE', '2023/11/10', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Carson', 'Lovel', 'clovel1d@xing.com', 'MALE', '2023/07/27', 'Azerbaijan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Beryle', 'Darbishire', 'bdarbishire1e@drupal.org', 'FEMALE', '2023/05/26', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Latashia', 'MacQuist', null, 'FEMALE', '2023/08/12', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tuesday', 'Yearron', 'tyearron1g@merriam-webster.com', 'FEMALE', '2023/09/21', 'Sweden');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Alard', 'Phlipon', 'aphlipon1h@cbc.ca', 'MALE', '2023/06/30', 'Sweden');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Hamil', 'Djurisic', 'hdjurisic1i@soundcloud.com', 'MALE', '2023/08/13', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Melinde', 'Lochead', 'mlochead1j@youtube.com', 'FEMALE', '2022/12/31', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Barbey', 'Rounce', 'brounce1k@ehow.com', 'FEMALE', '2023/09/24', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Rayner', 'Tierny', 'rtierny1l@ox.ac.uk', 'MALE', '2023/11/01', 'Tajikistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Bentlee', 'Haistwell', 'bhaistwell1m@indiegogo.com', 'MALE', '2023/07/12', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Clementia', 'MacDuff', 'cmacduff1n@engadget.com', 'FEMALE', '2023/04/16', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ludovico', 'O''Hegertie', null, 'MALE', '2023/03/04', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Maryl', 'Davson', null, 'MALE', '2022/12/28', 'Albania');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Bendite', 'Fowell', 'bfowell1q@google.com', 'FEMALE', '2023/08/18', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Aron', 'Addinall', 'aaddinall1r@oakley.com', 'MALE', '2023/04/02', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Barth', 'Autrie', 'bautrie1s@sun.com', 'MALE', '2022/12/16', 'Honduras');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Vlad', 'Kamien', 'vkamien1t@dailymail.co.uk', 'MALE', '2023/10/20', 'Canada');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Natalina', 'Mityushkin', 'nmityushkin1u@aboutads.info', 'FEMALE', '2023/06/20', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jud', 'Aleshkov', 'jaleshkov1v@51.la', 'MALE', '2022/12/11', 'Costa Rica');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Davidson', 'Franzke', null, 'MALE', '2023/05/09', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Randie', 'Maceur', 'rmaceur1x@jalbum.net', 'MALE', '2023/07/31', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Dru', 'Minchinton', null, 'FEMALE', '2023/02/21', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Iosep', 'Glinde', 'iglinde1z@exblog.jp', 'MALE', '2023/06/27', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lusa', 'Berthomier', null, 'FEMALE', '2023/05/28', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Annabella', 'Pendrid', 'apendrid21@yelp.com', 'FEMALE', '2023/07/14', 'New Zealand');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Arte', 'Matthewson', 'amatthewson22@hugedomains.com', 'MALE', '2022/12/03', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sallee', 'Proswell', 'sproswell23@sitemeter.com', 'FEMALE', '2023/01/03', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Franciskus', 'Enrique', 'fenrique24@merriam-webster.com', 'MALE', '2023/01/30', 'Colombia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marcel', 'Durward', null, 'Agender', '2023/03/24', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Zitella', 'Murrison', 'zmurrison26@mediafire.com', 'FEMALE', '2023/03/04', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Peterus', 'Nye', 'pnye27@odnoklassniki.ru', 'MALE', '2023/04/22', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Maurita', 'Andreutti', null, 'FEMALE', '2023/09/18', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Shandra', 'Grimolbie', 'sgrimolbie29@cam.ac.uk', 'FEMALE', '2023/06/21', 'Venezuela');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Erminia', 'Bassett', 'ebassett2a@ameblo.jp', 'FEMALE', '2023/05/08', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Alix', 'Cowl', 'acowl2b@phpbb.com', 'MALE', '2023/11/10', 'Spain');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Frazer', 'Linge', null, 'MALE', '2023/08/12', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ernesto', 'Antonat', 'eantonat2d@chron.com', 'MALE', '2023/05/25', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Rosco', 'Billanie', 'rbillanie2e@mayoclinic.com', 'MALE', '2023/05/06', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Flori', 'Plante', null, 'FEMALE', '2022/12/12', 'Estonia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Hattie', 'O''Bradane', 'hobradane2g@tinyurl.com', 'FEMALE', '2023/08/14', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Devin', 'Childerley', null, 'FEMALE', '2023/08/23', 'Bolivia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Vaughan', 'Heasman', 'vheasman2i@google.ca', 'MALE', '2023/08/29', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Bord', 'Metheringham', 'bmetheringham2j@java.com', 'MALE', '2023/10/21', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Delmore', 'Roels', 'droels2k@cnet.com', 'MALE', '2023/09/03', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Simeon', 'Izakoff', null, 'MALE', '2023/06/27', 'South Africa');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Hymie', 'Pues', 'hpues2m@amazon.co.uk', 'MALE', '2023/07/10', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Byrom', 'Silly', 'bsilly2n@arizona.edu', 'MALE', '2023/09/11', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Maureen', 'Pigny', 'mpigny2o@scribd.com', 'FEMALE', '2023/09/10', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tani', 'Emslie', 'temslie2p@github.com', 'MALE', '2023/08/17', 'Croatia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Arlyn', 'Medhurst', null, 'FEMALE', '2023/03/08', 'Sweden');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lyndy', 'Manifold', null, 'FEMALE', '2023/07/11', 'China');
